import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import RideRequest from '@/components/RideRequest'
import React from 'react'
import Contact from '@/components/Contact'
import AboutUs from '@/components/AboutUs'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ contact, setContact, ride, setRide }) {
  return (
    <>
      <Head>
        <title>Allure Taxi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="google-site-verification" content="sSa6de4r0cb3XLQiOM10TggDqOxUDGBNYrXU5EoeQY8" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <RideRequest
          ride={ride} setRide={setRide}
        />

        <AboutUs />
        <Contact contact={contact} setContact={setContact}/>

      </main>
    </>
  )
}
